# Generated by Django 2.0.6 on 2019-03-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodfitnessmodel',
            name='calories',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='foodfitnessmodel',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='foodfitnessmodel',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
